### ISSUE TITLE
Cannot import due to unfinished function definition in visualize.py

### ISSUE THREAD

**Issue by sophialilleengen** [EXP-code/EXP-tools#26]
[this line](https://github.com/EXP-code/EXP-tools/blob/6f4ce18eb4ce69489d6834b04151d15b11558d02/EXPtools/visuals/visualize.py#L5C1-L6C1) should be commented out. Cannot import EXPtools with this.

**Comment by jngaravitoc** [comment]
Hi @sophialilleengen, thanks for reporting this. I'm working on a new version, hopefully to come out in one week or so where all this is fixed!

**Comment by jngaravitoc** [comment]
I just fixed this in the last pull request https://github.com/EXP-code/EXP-tools/commit/5c0ac1d151bf5fb2af226978e6fe7a6346b87663
