### ISSUE TITLE
k3d needs to be added as required package to setup.py

### ISSUE THREAD

**Issue by sophialilleengen** [EXP-code/EXP-tools#27]
Otherwise there is a ModuleNotFoundError when importing EXPtools

**Comment by jngaravitoc** [comment]
Just fixed this in the last pull request See: [5c0ac1d151bf5fb2af226978e6fe7a6346b87663](https://github.com/EXP-code/EXP-tools/commit/5c0ac1d151bf5fb2af226978e6fe7a6346b87663)
